name: AppImage (Development Version)

on:
  # The button for manual dispatch only appear when it has been merged into the default branch
  push:
    branches: 'develop'
  workflow_dispatch:

jobs:
  Manylinux-Appimage:
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2014_x86_64
    env:
      APP_PYTHON_VERSION: "3.11"
    steps:
    - uses: actions/checkout@v3

    - name: Build AppImage
      working-directory: AppImage
      env:
        USE_CUTTING_EDGE_BACKENDS: 1
      run: bash build-ratarmount-appimage.sh

    - uses: actions/upload-artifact@v3
      with:
        name: ratarmount-manylinux2014_x86_64.AppImage
        path: AppImage/ratarmount-manylinux2014_x86_64.AppImage
